service: ec2-ezops

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

resources:
  Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: "ami-013f17f36f8b1fefb"
        InstanceType: t2.micro
        Tags:
          - Key: Name
            Value: ezops-teste
        KeyName: ezops-teste
        SecurityGroupIds:
          - sg-ed0d9fdc
        BlockDeviceMappings:
          - DeviceName: /dev/sdc
            Ebs:
              VolumeSize: 50
              VolumeType: io1
              Iops: 1000
              DeleteOnTermination: false

    TopicCloudwatchAlarm:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: topic-cloudwatch-alarm


    TopicCloudwatchAlarmSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: isabel.santos2600@gmail.com
        Protocol: email
        TopicArn:
          Ref: TopicCloudwatchAlarm